### ISSUE TITLE
This is stolen code from @rozari0

### ISSUE THREAD

**Issue by kevlened** [DX-MODS/SpotifyDL#3]
As mentioned in https://github.com/DX-MODS/SpotifyDL/issues/2

The MIT license requires attribution to the original developer. You are permitted to relicense the code as AGPL, but the files with substantial portions of the original code must contain the original license.

Here's a file you started with: https://github.com/DX-MODS/SpotifyDL/blob/87a1361442fcc9940b366d8fae65810647545f44/mbot/plugins/deezer.py

And here's the same file after infringement: https://github.com/DX-MODS/SpotifyDL/blob/1f78a96fb6d96a687920afa114250c626da7e2ab/dxbotz/plugins/deezer.py

And here's Daniel's original repo: https://github.com/rozari0/NeedMusicRobot

I'd advise to re-add Daniel's license to the offending files. Alternatively, consider contributing to Daniel's original project.

Without adding his license, your AGPL license has no teeth. If someone were to infringe on your license, you could not stop them. Daniel, however, could enforce his license if you were to ever profit from this project.

Edit: I find it unusual that [Masterolic/Spotify-Downloader](https://github.com/Masterolic/Spotify-Downloader) would retain Daniel's license, but SpotifyDL does not.

**Comment by DX-MODS** [comment]
Bro sorry its my mistake
